sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  wechat:
    appid : wxc17bf4c88a13cc3c
    secret : e4877f30a5403de7ae130cac987c4e5c